#! /usr/bin/env bash

set -e

#readonly DOCKER_USER="${USER:-root}"
readonly DOCKER_USER="rumono"
readonly PWD=`pwd`
docker run -it --privileged=true -v ${PWD}:/home/${DOCKER_USER}/RuMono --name rumono rumono:v0.1
