#! /usr/bin/env bash

set -e

cargo install afl --version 0.13.5 --locked

# Get host target
host=$(rustc -vV | grep '^host:' | cut -d' ' -f2)
# Download binary and install to $HOME/.cargo/bin
curl --proto '=https' --tlsv1.2 -fsSL "https://github.com/taiki-e/cargo-llvm-cov/releases/latest/download/cargo-llvm-cov-$host.tar.gz" \
  | tar xzf - -C "$HOME/.cargo/bin"

SCRIPT_DIR=$(dirname "$(readlink -f "$0")")
PARENT_DIR=$(dirname "$SCRIPT_DIR")
RUMONO_DIR="$PARENT_DIR/rumono"

if [ ! -d "$RUMONO_DIR" ]; then
    echo "Error: $RUMONO_DIR does not exist"
    exit 1
fi

if [[ ":$PATH:" == *":$RUMONO_DIR:"* ]]; then
    echo "$RUMONO_DIR is already in PATH"
else
    echo "export PATH=\"$RUMONO_DIR:\$PATH\"" >> "$HOME/.bashrc"
    echo "Added $RUMONO_DIR to PATH permanently in $HOME/.bashrc"
    echo "Please run 'source ~/.bashrc' to apply changes immediately."
fi
